micronaut:
    application:
        name: bookcatalogue
    server:
        port: 8081

consul:
    client:
        registration:
            enabled: true
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
                
#Uncomment to set server port
#    server:
#        port: 8080
